package com.raki.AutoCrankBackEnd.Model;
import java.util.List;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

@Entity
@Table
@Component

public class Supplier {
	@Id
	private String supplierId;
	private String supplierName;
	private String supplierAddress;
	private String SupplierPh_no;

	public Supplier() {
		// TODO Auto-generated constructor stub
		this.supplierId = "SUPP" + UUID.randomUUID().toString().substring(30).toUpperCase();
	}

	@OneToMany(mappedBy = "supplier")
	private List<Product> product;

//generated by @OneToMany
	public List<Product> getProduct() {
		return product;
	}

	public void setProduct(List<Product> product) {
		this.product = product;
	}
	// generated by attributes

	public String getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(String supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getSupplierAddress() {
		return supplierAddress;
	}

	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	public String getSupplierPh_no() {
		return SupplierPh_no;
	}

	public void setSupplierPh_no(String supplierPh_no) {
		SupplierPh_no = supplierPh_no;
	}

}
