package com.raki.AutoCrankBackEnd.Model;

import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.springframework.stereotype.Component;

@Entity
@Table
@Component
public class User {
	@Id
	private String userId;
	private String userName;
	private String useraddress;
	private String userPh_no;
	private String userEmailId;
	private String userPassword;

	public User() {
		// TODO Auto-generated constructor stub
		this.userId = "USER" + UUID.randomUUID().toString().substring(30).toUpperCase();
	}

	@OneToOne
	@JoinColumn(name = "billingId")
	private Billing billing;

	@OneToOne
	@JoinColumn(name = "orderId")
	private Order order;

	@OneToOne
	@JoinColumn(name = "shippingId")
	private Shipping shipping;

	public Shipping getShipping() {
		return shipping;
	}

	public void setShipping(Shipping shipping) {
		this.shipping = shipping;
	}

	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	// generated by @oneToOne
	public Billing getBilling() {
		return billing;
	}

	public void setBilling(Billing billing) {
		this.billing = billing;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUseraddress() {
		return useraddress;
	}

	public void setUseraddress(String useraddress) {
		this.useraddress = useraddress;
	}

	public String getUserPh_no() {
		return userPh_no;
	}

	public void setUserPh_no(String userPh_no) {
		this.userPh_no = userPh_no;
	}

	public String getUserEmailId() {
		return userEmailId;
	}

	public void setUserEmailId(String userEmailId) {
		this.userEmailId = userEmailId;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

}
